### PR TITLE
Add screen class

### PR DESCRIPTION
**Pull request by Tekito-256**
Add a Screen class.  This class contains functions used for 3DS screen drawing.

### CODE REVIEW

**Comment by HIDE810** [comment]
There is a build error on Linux. Windows doesn't have this problem. Further investigation is required.

image

**Comment by Tekito-256** [comment]
> There is a build error with the latest libctru. Further investigation is required.
> 
> image

Fixed by this commit.
https://github.com/Maru-pika/NCTRPF/pull/11/commits/b409f316c034af3a3565439aa9d5a18464067d67

**Comment by Tekito-256** [comment]
Use this libctru to build. 
https://github.com/Tekito-256/libctru/tree/syscallExt

**Comment by Tekito-256** [comment]
No changes to libctru are required.

**Comment by HIDE810** [comment]
Merged, thanks!

**Pull request merged**
